// utils/pdf.js
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Create a PDFDocument with a school header and consistent margins.
 * @param {Object} opts
 * @param {Object} opts.settings  - school settings (name, logo, address, etc.)
 * @param {Object} opts.title     - document title, e.g. "Payment Receipt"
 */
function createDoc({ settings, title }) {
    const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
        info: {
            Title: title,
            Author: settings.SCHOOL_NAME || 'School',
            Creator: 'School Management System',
        },
    });

    // Header: logo + school info
    drawHeader(doc, settings, title);

    return doc;
}

function drawHeader(doc, settings, title) {
    const top = 40;
    const logoSize = 50;

    // Logo (if file exists)
    if (settings.SCHOOL_LOGO) {
        const logoPath = path.join(__dirname, '..', settings.SCHOOL_LOGO.replace(/^\//, ''));
        if (fs.existsSync(logoPath)) {
            doc.image(logoPath, 40, top, { width: logoSize, height: logoSize });
        }
    }

    // School name
    doc
        .font('Helvetica-Bold')
        .fontSize(16)
        .text(settings.SCHOOL_NAME || 'School', 100, top, { width: 400 });

    doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor('#666')
        .text(settings.SCHOOL_ADDRESS || '', 100, top + 20, { width: 400 });

    doc
        .fontSize(9)
        .text(
            [
                settings.SCHOOL_PHONE ? `Phone: ${settings.SCHOOL_PHONE}` : null,
                settings.SCHOOL_EMAIL ? `Email: ${settings.SCHOOL_EMAIL}` : null,
            ]
                .filter(Boolean)
                .join('  |  '),
            100,
            top + 32,
            { width: 400 }
        );

    // Title on the right
    doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor('#000')
        .text(title.toUpperCase(), 400, top + 10, { width: 155, align: 'right' });

    // Divider
    doc
        .moveTo(40, top + 60)
        .lineTo(doc.page.width - 40, top + 60)
        .strokeColor('#ddd')
        .lineWidth(1)
        .stroke();

    doc.fillColor('#000');
    doc.y = top + 75;
}

function drawFooter(doc, settings) {
    const bottom = doc.page.height - 40;
    doc
        .font('Helvetica')
        .fontSize(8)
        .fillColor('#999')
        .text(
            settings.FOOTER_TEXT || `Generated by ${settings.SCHOOL_NAME || 'School'} Management System`,
            40,
            bottom,
            { width: doc.page.width - 80, align: 'center' }
        );
    doc.fillColor('#000');
}

/**
 * Finalize a PDF into a Buffer.
 */
function toBuffer(doc) {
    return new Promise((resolve, reject) => {
        const chunks = [];
        doc.on('data', c => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
        doc.end();
    });
}

module.exports = { createDoc, drawFooter, toBuffer };