// models/Attendance.js - UPDATED VERSION
const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema({
    student: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Student',
        required: true
    },
    teacher: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Teacher'
    },
    class: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Class',
        required: true
    },
    subject: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Subject',
        required: true
    },
    date: {
        type: Date,
        required: true
    },
    day: {
        type: String,
        enum: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    },
    status: {
        type: String,
        enum: ['present', 'absent', 'late', 'half_day', 'excused', 'holiday'],
        default: 'present'
    },
    period: {
        type: Number,
        required: true,
        min: 1,
        max: 12
    },
    periodTimeRange: {
        start: String, // "HH:MM"
        end: String    // "HH:MM"
    },
    recordedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    remarks: String,
    // For bulk attendance marking
    sessionType: {
        type: String,
        enum: ['morning', 'afternoon', 'full_day'],
        default: 'full_day'
    },
    isAutoGenerated: {
        type: Boolean,
        default: false
    }
}, { timestamps: true });

// Compound indexes for performance
attendanceSchema.index({
    student: 1,
    subject: 1,
    date: 1,
    period: 1
}, { unique: true });

attendanceSchema.index({ class: 1, date: 1, period: 1 });
attendanceSchema.index({ date: 1, day: 1, class: 1 });
attendanceSchema.index({ student: 1, date: 1 });
attendanceSchema.index({ teacher: 1, date: 1 });

module.exports = mongoose.model('Attendance', attendanceSchema);

// // models/Attendance.js - UPDATED VERSION
// const mongoose = require('mongoose');

// const attendanceSchema = new mongoose.Schema({
//     student: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'Student',
//         required: true
//     },
//     teacher: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'Teacher'
//     },
//     class: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'Class',
//         required: true
//     },
//     subject: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'Subject',
//         required: true
//     },
//     date: {
//         type: Date,
//         required: true
//     },
//     day: {
//         type: String,
//         enum: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
//     },
//     status: {
//         type: String,
//         enum: ['present', 'absent', 'late', 'half_day', 'excused', 'holiday'],
//         default: 'present'
//     },
//     period: {
//         type: Number,
//         required: true,
//         min: 1,
//         max: 12
//     },
//     periodTimeRange: {
//         start: String, // "HH:MM"
//         end: String    // "HH:MM"
//     },
//     recordedBy: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'User',
//         required: true
//     },
//     remarks: String,
//     // For bulk attendance marking
//     sessionType: {
//         type: String,
//         enum: ['morning', 'afternoon', 'full_day'],
//         default: 'full_day'
//     },
//     isAutoGenerated: {
//         type: Boolean,
//         default: false
//     }
// }, { timestamps: true });

// // Compound indexes for performance
// attendanceSchema.index({
//     student: 1,
//     subject: 1,
//     date: 1,
//     period: 1
// }, { unique: true });

// attendanceSchema.index({ class: 1, date: 1, period: 1 });
// attendanceSchema.index({ date: 1, day: 1, class: 1 });
// attendanceSchema.index({ student: 1, date: 1 });
// attendanceSchema.index({ teacher: 1, date: 1 });

// module.exports = mongoose.model('Attendance', attendanceSchema);
